name: Mirror Repo
on:
  push:
     branches:
       - main

jobs:
  mirror-repo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Push To Mirror
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
            #GIT_CONFIG_COUNT=2
            #GIT_CONFIG_KEY_0='credential.https://github.com.username'
            #GIT_CONFIG_VALUE_0=x-access-token
            #GIT_CONFIG_KEY_1='credential.https://github.com.helper'
            #GIT_CONFIG_VALUE_1='!f() { test "$1" = get && echo "password=${GIT_TOKEN}"; }; f'
            git remote set-url origin ${{ vars.GIT_MIRROR }}
            git config --unset http.https://github.com/.extraheader
            git config credential.https://github.com.username "x-access-token"
            git config credential.https://github.com.helper ${GIT_TOKEN}
            git config --list --show-origin
            git push -u origin main
